### ISSUE TITLE
Clicking on movie does nothing

### ISSUE THREAD

**Issue by Alaskanyoda** [FireAstrox/CS372#12]
When a movie has an invalid YouTube link defined, the viewer is not taken to the movie page when the movie is clicked on, as such failing test case 1. There is no error msg or anything, so from the viewer's perspective it simply does not work. I would consider this case passed if the viewer had some way of knowing this movie was unavailable.

**Comment by FireAstrox** [comment]
This is a duplicate issue of #7. Only youtube links are allowed to be input for the content manager. There is no specific restriction to reject other links currently just text in the content add page stating that it needs to be a youtube link. I can add a check for specific youtube links as to prevent any invalid URLs from being entered.

**Comment by FireAstrox** [comment]
This has now been fixed and only allows valid youtube links in the format noted in Issue #7, this will also be added to the documentation. Please retest for this
