### ISSUE TITLE
When installing on linux be sure to specify starting the mongodb service in systemd

### ISSUE THREAD

**Issue by yeSpud** [FireAstrox/CS372#6]
There may be an issue with mongodb not running on linux and erroring out when you try to connect with compass.

Ive found that this can be resolved by making sure that the mongodb service is running by doing `sudo systemctl start mongodb.service`

**Comment by FireAstrox** [comment]
Just to make sure im following for documentation, Linus does not automatically start the mongodb service and needs to be first started with `sudo systemctl start mongodb.service` in order to connect to compass properly?

**Comment by Alaskanyoda** [comment]
When running this command I get the error "Failed to start mongodb.service: Unit mongodb.service not found.

**Comment by FireAstrox** [comment]
To fix this issue please try running

`sudo apt-get install gnupg curl`

followed by 
`curl -fsSL https://www.mongodb.org/static/pgp/server-7.0.asc | \sudo gpg -o /usr/share/keyrings/mongodb-server-7.0.gpg \--dearmor`

then 
`echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-7.0.list`

then run `sudo apt-get update` to update all the packages

finally run `sudo apt-get install -y mongodb-org` to install the most recent version of mongodb

the command to run mongodb will be `sudo systemctl start mongod`

for further detail please follow this link: https://www.mongodb.com/docs/manual/tutorial/install-mongodb-on-ubuntu/

**Comment by Alaskanyoda** [comment]
I opened MongoDB compass through the shell and received the error: "gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!" when trying to press connect. Upon further research this is a problem with my version of Ubuntu (22.04.4) and is apparently only fixable by downgrading.
More information can be found at: https://github.com/electron/electron/issues/32760

**Comment by FireAstrox** [comment]
I think you might have something installed incorrectly as I did this on Ubuntu 22.04.4 and was able to open compass through the shell as well as getting it to connect with mongodb

**Comment by Alaskanyoda** [comment]
Problem: mongodb not starting correctly. (exit code 14)
Solution: 
run sudo rm /tmp/mongodb-27017.sock
run sudo systemctl restart mongod
Notes: problem was hard to detect because when running sudo systemctl start mongod, it shows no signs of failing, you can only see the failure if you run sudo systemctl status mongod and see that the db is not up, and had exit code 14.
