### ISSUE TITLE
Nothing happens when clicking on a movie

### ISSUE THREAD

**Issue by yeSpud** [FireAstrox/CS372#7]
When entering a new movie pointing to `example.com` it adds to the database successfully and is shown to the user, but when clicking on the movie nothing happens.

**Comment by FireAstrox** [comment]
A valid youtube.com url is required when adding a movie for a movie to play 
Ex: 
https://www.youtube.com/watch?v=njX2bu-_Vw4&t=8s or 
https://youtu.be/njX2bu-_Vw4

**Comment by yeSpud** [comment]
Would be neat if there was [placeholder text](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/placeholder#example) for the movie uelz because I thought any url would work, but this is me mostly just spit balling

**Comment by FireAstrox** [comment]
I agree, we can make it more clear and add that change
